language: csharp
dist: bionic
mono: none
#must declare version
dotnet: 2.2.401
script:
 - dotnet test -c Release
 - cd ./USFMToolsSharp/bin/Release/
 - PKG_NAME=$(ls *.nupkg)
 - if [ -n "$TRAVIS_TAG" ]; then dotnet nuget push $PKG_NAME -k $NUGET_TOKEN -s https://api.nuget.org/v3/index.json; fi
