using System;
using System.Collections.Frozen;
using System.Collections.Generic;
using System.Linq;
using USFMToolsSharp.Models;
using USFMToolsSharp.Models.Markers;

namespace USFMToolsSharp;

public static class DefaultHierarchies
{
    public static readonly Dictionary<Type, HierarchyDefinition> Default = new()
    {
        [typeof(ADDMarker)] = new HierarchyDefinition([typeof(TextBlock)]),
        [typeof(BDITMarker)] = new HierarchyDefinition([typeof(TextBlock)]),
        [typeof(BDMarker)] = new HierarchyDefinition([typeof(TextBlock)]),
        [typeof(CLSMarker)] = new HierarchyDefinition([typeof(TextBlock)]),
        [typeof(CMarker)] = new HierarchyDefinition([
            typeof(MMarker),
            typeof(MSMarker),
            typeof(SMarker),
            typeof(BMarker),
            typeof(DMarker),
            typeof(VMarker),
            typeof(PMarker),
            typeof(PCMarker),
            typeof(PMMarker),
            typeof(CDMarker),
            typeof(CPMarker),
            typeof(DMarker),
            typeof(CLMarker),
            typeof(QMarker),
            typeof(QSMarker),
            typeof(QSEndMarker),
            typeof(QAMarker),
            typeof(QMarker),
            typeof(NBMarker),
            typeof(RMarker),
            typeof(LIMarker),
            typeof(TableBlock),
            typeof(MMarker),
            typeof(MIMarker),
            typeof(PIMarker),
            typeof(CAMarker),
            typeof(CAEndMarker),
            typeof(SPMarker),
            typeof(TextBlock),
            typeof(REMMarker),
            typeof(DMarker),
            typeof(VAMarker),
            typeof(VAEndMarker),
            typeof(FMarker),
            typeof(FEndMarker),
        ]),
        [typeof(DMarker)] = new HierarchyDefinition([
            typeof(FMarker),
            typeof(FEndMarker),
            typeof(ITMarker),
            typeof(ITEndMarker),
            typeof(TextBlock),
        ]),
        [typeof(EMMarker)] = new HierarchyDefinition([typeof(TextBlock)]),
        [typeof(FLMarker)] = new HierarchyDefinition([typeof(TextBlock)]),
        [typeof(FMarker)] = new HierarchyDefinition([
            typeof(FRMarker),
            typeof(FREndMarker),
            typeof(FKMarker),
            typeof(FTMarker),
            typeof(FVMarker),
            typeof(FVEndMarker),
            typeof(FPMarker),
            typeof(FQAMarker),
            typeof(FQAEndMarker),
            typeof(FQMarker),
            typeof(FQEndMarker),
            typeof(TLMarker),
            typeof(TLEndMarker),
            typeof(WMarker),
            typeof(WEndMarker),
            typeof(TextBlock),
            typeof(ITMarker),
            typeof(ITEndMarker),
            typeof(SCMarker),
            typeof(SCEndMarker),
            typeof(SUPMarker),
            typeof(SUPEndMarker),
            typeof(BKMarker),
            typeof(BKEndMarker),
            typeof(BDMarker),
            typeof(BDEndMarker),
            typeof(FLMarker),
        ]),
        [typeof(FPMarker)] = new HierarchyDefinition([typeof(TextBlock)]),
        [typeof(FQAMarker)] = new HierarchyDefinition([
            typeof(TextBlock),
            typeof(TLMarker),
            typeof(TLEndMarker),
            typeof(WMarker),
            typeof(WEndMarker),
        ]),
        [typeof(FQMarker)] = new HierarchyDefinition([
            typeof(TextBlock),
            typeof(TLMarker),
            typeof(TLEndMarker),
            typeof(WMarker),
            typeof(WEndMarker),
        ]),
        [typeof(FTMarker)] = new HierarchyDefinition([
            typeof(TLMarker),
            typeof(TLEndMarker),
            typeof(WMarker),
            typeof(WEndMarker),
            typeof(TextBlock),
            typeof(ITMarker),
            typeof(ITEndMarker),
            typeof(SCMarker),
            typeof(SCEndMarker),
            typeof(SUPMarker),
            typeof(SUPEndMarker),
            typeof(BKMarker),
            typeof(BKEndMarker),
            typeof(BDMarker),
            typeof(BDEndMarker),
        ]),
        [typeof(IQMarker)] = new HierarchyDefinition([typeof(TextBlock)]),
        [typeof(ILIMarker)] = new HierarchyDefinition([typeof(TextBlock)]),
        [typeof(IMMarker)] = new HierarchyDefinition([
            typeof(TextBlock),
            typeof(BKMarker),
            typeof(BKEndMarker),
            typeof(BDMarker),
            typeof(BDEndMarker),
            typeof(ITMarker),
            typeof(ITEndMarker),
        ]),
        [typeof(IMIMarker)] = new HierarchyDefinition([
            typeof(TextBlock),
            typeof(BKMarker),
            typeof(BKEndMarker),
            typeof(BDMarker),
            typeof(BDEndMarker),
            typeof(ITMarker),
            typeof(ITEndMarker),
        ]),
        [typeof(IMQMarker)] = new HierarchyDefinition([
            typeof(TextBlock),
            typeof(BKMarker),
            typeof(BKEndMarker),
            typeof(BDMarker),
            typeof(BDEndMarker),
            typeof(ITMarker),
            typeof(ITEndMarker),
        ]),
        [typeof(IOMarker)] = new HierarchyDefinition([
            typeof(TextBlock),
            typeof(IORMarker),
            typeof(IOREndMarker),
        ]),
        [typeof(IORMarker)] = new HierarchyDefinition([typeof(TextBlock)]),
        [typeof(IPMarker)] = new HierarchyDefinition([
            typeof(TextBlock),
            typeof(BKMarker),
            typeof(BKEndMarker),
            typeof(BDMarker),
            typeof(BDEndMarker),
            typeof(ITMarker),
            typeof(ITEndMarker),
            typeof(SCMarker),
            typeof(SCEndMarker),
            typeof(BDITMarker),
            typeof(BDITEndMarker),
            typeof(NDMarker),
            typeof(NDEndMarker),
            typeof(NOMarker),
            typeof(NOEndMarker),
            typeof(SUPMarker),
            typeof(SUPEndMarker),
            typeof(IEMarker),
            typeof(RQMarker),
            typeof(RQEndMarker),
        ]),
        [typeof(IPIMarker)] = new HierarchyDefinition([
            typeof(TextBlock),
            typeof(BKMarker),
            typeof(BKEndMarker),
            typeof(BDMarker),
            typeof(BDEndMarker),
            typeof(ITMarker),
            typeof(ITEndMarker),
            typeof(SCMarker),
            typeof(SCEndMarker),
            typeof(BDITMarker),
            typeof(BDITEndMarker),
            typeof(NDMarker),
            typeof(NDEndMarker),
            typeof(NOMarker),
            typeof(NOEndMarker),
            typeof(SUPMarker),
            typeof(SUPEndMarker),
        ]),
        [typeof(IPQMarker)] = new HierarchyDefinition([
            typeof(TextBlock),
            typeof(BKMarker),
            typeof(BKEndMarker),
            typeof(BDMarker),
            typeof(BDEndMarker),
            typeof(ITMarker),
            typeof(ITEndMarker),
            typeof(SCMarker),
            typeof(SCEndMarker),
            typeof(BDITMarker),
            typeof(BDITEndMarker),
            typeof(NDMarker),
            typeof(NDEndMarker),
            typeof(NOMarker),
            typeof(NOEndMarker),
            typeof(SUPMarker),
            typeof(SUPEndMarker),
        ]),
        [typeof(IPRMarker)] = new HierarchyDefinition([
            typeof(TextBlock),
            typeof(BKMarker),
            typeof(BKEndMarker),
            typeof(BDMarker),
            typeof(BDEndMarker),
            typeof(ITMarker),
            typeof(ITEndMarker),
            typeof(SCMarker),
            typeof(SCEndMarker),
            typeof(BDITMarker),
            typeof(BDITEndMarker),
            typeof(NDMarker),
            typeof(NDEndMarker),
            typeof(NOMarker),
            typeof(NOEndMarker),
            typeof(SUPMarker),
            typeof(SUPEndMarker),
        ]),
        [typeof(ITMarker)] = new HierarchyDefinition([typeof(TextBlock)]),
        [typeof(KMarker)] = new HierarchyDefinition([typeof(TextBlock)]),
        [typeof(LFMarker)] = new HierarchyDefinition([typeof(TextBlock)]),
        [typeof(LIMarker)] = new HierarchyDefinition([
            typeof(VMarker),
            typeof(TextBlock),
        ]),
        [typeof(LIVMarker)] = new HierarchyDefinition([typeof(TextBlock)]),
        [typeof(MMarker)] = new HierarchyDefinition([
            typeof(VMarker),
            typeof(TextBlock),
            typeof(BKMarker),
            typeof(BKEndMarker),
            typeof(BDMarker),
            typeof(BDEndMarker),
            typeof(ITMarker),
            typeof(ITEndMarker),
            typeof(SCMarker),
            typeof(SCEndMarker),
            typeof(BDITMarker),
            typeof(BDITEndMarker),
            typeof(NDMarker),
            typeof(NDEndMarker),
            typeof(NOMarker),
            typeof(NOEndMarker),
            typeof(SUPMarker),
            typeof(SUPEndMarker),
        ]),
        [typeof(MIMarker)] = new HierarchyDefinition([
            typeof(TextBlock),
            typeof(VMarker),
            typeof(BKMarker),
            typeof(BKEndMarker),
            typeof(BDMarker),
            typeof(BDEndMarker),
            typeof(ITMarker),
            typeof(ITEndMarker),
            typeof(SCMarker),
            typeof(SCEndMarker),
            typeof(BDITMarker),
            typeof(BDITEndMarker),
            typeof(NDMarker),
            typeof(NDEndMarker),
            typeof(NOMarker),
            typeof(NOEndMarker),
            typeof(SUPMarker),
            typeof(SUPEndMarker),
        ]),
        [typeof(MRMarker)] = new HierarchyDefinition([
            typeof(FMarker),
            typeof(FEndMarker),
        ]),
        [typeof(MSMarker)] = new HierarchyDefinition([typeof(MRMarker)]),
        [typeof(NDMarker)] = new HierarchyDefinition([typeof(TextBlock)]),
        [typeof(NOMarker)] = new HierarchyDefinition([typeof(TextBlock)]),
        [typeof(ORDMarker)] = new HierarchyDefinition([typeof(TextBlock)]),
        [typeof(PMarker)] = new HierarchyDefinition([
            typeof(VMarker),
            typeof(BMarker),
            typeof(SPMarker),
            typeof(TextBlock),
            typeof(FMarker),
            typeof(FEndMarker),
            typeof(LIMarker),
            typeof(QMarker),
            typeof(XMarker),
            typeof(SCMarker),
        ]),
        [typeof(PCMarker)] = new HierarchyDefinition([
            typeof(VMarker),
            typeof(BMarker),
            typeof(SPMarker),
            typeof(TextBlock),
            typeof(FMarker),
            typeof(FEndMarker),
            typeof(LIMarker),
            typeof(QMarker),
            typeof(SCMarker),
        ]),
        [typeof(PIMarker)] = new HierarchyDefinition([
            typeof(VMarker),
            typeof(BMarker),
            typeof(SPMarker),
            typeof(TextBlock),
            typeof(FMarker),
            typeof(FEndMarker),
            typeof(LIMarker),
            typeof(QMarker),
        ]),
        [typeof(PMMarker)] = new HierarchyDefinition([
            typeof(VMarker),
            typeof(BMarker),
            typeof(SPMarker),
            typeof(TextBlock),
            typeof(FMarker),
            typeof(FEndMarker),
            typeof(LIMarker),
            typeof(QMarker),
            typeof(XMarker),
            typeof(SCMarker),
        ]),
        [typeof(PMCMarker)] = new HierarchyDefinition([typeof(TextBlock)]),
        [typeof(PMOMarker)] = new HierarchyDefinition([typeof(TextBlock)]),
        [typeof(PMRMarker)] = new HierarchyDefinition([typeof(TextBlock)]),
        [typeof(PNMarker)] = new HierarchyDefinition([typeof(TextBlock)]),
        [typeof(PNGMarker)] = new HierarchyDefinition([typeof(TextBlock)]),
        [typeof(PROMarker)] = new HierarchyDefinition([typeof(TextBlock)]),
        [typeof(PRMarker)] = new HierarchyDefinition([typeof(TextBlock)]),
        [typeof(QAMarker)] = new HierarchyDefinition([
            typeof(QACMarker),
            typeof(QACEndMarker),
        ]),
        [typeof(QCMarker)] = new HierarchyDefinition([
            typeof(TextBlock),
            typeof(FMarker),
            typeof(FEndMarker),
            typeof(TLMarker),
            typeof(TLEndMarker),
            typeof(WMarker),
            typeof(WEndMarker),
        ]),
        [typeof(QDMarker)] = new HierarchyDefinition([
            typeof(TextBlock),
            typeof(FMarker),
            typeof(FEndMarker),
            typeof(TLMarker),
            typeof(TLEndMarker),
            typeof(WMarker),
            typeof(WEndMarker),
        ]),
        [typeof(QMMarker)] = new HierarchyDefinition([
            typeof(TextBlock),
            typeof(FMarker),
            typeof(FEndMarker),
            typeof(TLMarker),
            typeof(TLEndMarker),
            typeof(WMarker),
            typeof(WEndMarker),
        ]),
        [typeof(QMarker)] = new HierarchyDefinition([
            typeof(BMarker),
            typeof(QSMarker),
            typeof(QSEndMarker),
            typeof(TextBlock),
            typeof(FMarker),
            typeof(FEndMarker),
            typeof(TLMarker),
            typeof(TLEndMarker),
            typeof(WMarker),
            typeof(WEndMarker),
            typeof(VMarker),
        ]){ CanInsert = (type, node, marker) =>
        {
            return marker is not VMarker || !(node.HasChildren && node.Contents.Any(m => m.Marker is VMarker));
        }},
        [typeof(QRMarker)] = new HierarchyDefinition([
            typeof(TextBlock),
            typeof(FMarker),
            typeof(FEndMarker),
            typeof(TLMarker),
            typeof(TLEndMarker),
            typeof(WMarker),
            typeof(WEndMarker),
        ]),
        [typeof(QSMarker)] = new HierarchyDefinition([typeof(TextBlock)]),
        [typeof(QTMarker)] = new HierarchyDefinition([typeof(TextBlock)]),
        [typeof(RBMarker)] = new HierarchyDefinition([typeof(TextBlock)]),
        [typeof(RMarker)] = new HierarchyDefinition([typeof(TextBlock)]),
        [typeof(RQMarker)] = new HierarchyDefinition([typeof(TextBlock)]),
        [typeof(SMarker)] = new HierarchyDefinition([
            typeof(RMarker),
            typeof(FMarker),
            typeof(FEndMarker),
            typeof(SCMarker),
            typeof(SCEndMarker),
            typeof(EMMarker),
            typeof(EMEndMarker),
            typeof(BDMarker),
            typeof(BDEndMarker),
            typeof(ITMarker),
            typeof(ITEndMarker),
            typeof(BDITMarker),
            typeof(BDITEndMarker),
            typeof(NOMarker),
            typeof(NOEndMarker),
            typeof(SUPMarker),
            typeof(SUPEndMarker),
            typeof(TextBlock),
        ]),
        [typeof(SCMarker)] = new HierarchyDefinition([typeof(TextBlock)]),
        [typeof(SIGMarker)] = new HierarchyDefinition([typeof(TextBlock)]),
        [typeof(SLSMarker)] = new HierarchyDefinition([typeof(TextBlock)]),
        [typeof(SUPMarker)] = new HierarchyDefinition([typeof(TextBlock)]),
        [typeof(TableBlock)] = new HierarchyDefinition([typeof(TRMarker)]),
        [typeof(TCMarker)] = new HierarchyDefinition([typeof(TextBlock)]),
        [typeof(TCRMarker)] = new HierarchyDefinition([typeof(TextBlock)]),
        [typeof(THMarker)] = new HierarchyDefinition([typeof(TextBlock)]),
        [typeof(THRMarker)] = new HierarchyDefinition([typeof(TextBlock)]),
        [typeof(TLMarker)] = new HierarchyDefinition([typeof(TextBlock)]),
        [typeof(TRMarker)] = new HierarchyDefinition([
            typeof(TCMarker),
            typeof(THMarker),
            typeof(TCRMarker),
            typeof(THRMarker),
        ]),
        [typeof(VMarker)] = new HierarchyDefinition([
            typeof(VPMarker),
            typeof(VPEndMarker),
            typeof(TLMarker),
            typeof(TLEndMarker),
            typeof(ADDMarker),
            typeof(ADDEndMarker),
            typeof(BMarker),
            typeof(BKMarker),
            typeof(BKEndMarker),
            typeof(BDMarker),
            typeof(BDEndMarker),
            typeof(ITMarker),
            typeof(ITEndMarker),
            typeof(EMMarker),
            typeof(EMEndMarker),
            typeof(BDITMarker),
            typeof(BDITEndMarker),
            typeof(SUPMarker),
            typeof(SUPEndMarker),
            typeof(NOMarker),
            typeof(NOEndMarker),
            typeof(SCMarker),
            typeof(SCEndMarker),
            typeof(NDMarker),
            typeof(NDEndMarker),
            typeof(QMarker),
            typeof(MMarker),
            typeof(FMarker),
            typeof(FEndMarker),
            typeof(FRMarker),
            typeof(FREndMarker),
            typeof(SPMarker),
            typeof(TextBlock),
            typeof(WMarker),
            typeof(WEndMarker),
            typeof(XMarker),
            typeof(XEndMarker),
            typeof(CLSMarker),
            typeof(RQMarker),
            typeof(RQEndMarker),
            typeof(PIMarker),
            typeof(MIMarker),
            typeof(QSMarker),
            typeof(QSEndMarker),
            typeof(QRMarker),
            typeof(QCMarker),
            typeof(QDMarker),
            typeof(QACMarker),
            typeof(QACEndMarker),
            typeof(SMarker),
            typeof(VAMarker),
            typeof(VAEndMarker),
            typeof(KMarker),
            typeof(KEndMarker),
            typeof(LFMarker),
            typeof(LIKMarker),
            typeof(LIKEndMarker),
            typeof(LITLMarker),
            typeof(LITLEndMarker),
            typeof(LIVMarker),
            typeof(LIMarker),
            typeof(LIVEndMarker),
            typeof(ORDMarker),
            typeof(ORDEndMarker),
            typeof(PMCMarker),
            typeof(PMOMarker),
            typeof(PMRMarker),
            typeof(PNGMarker),
            typeof(PNGEndMarker),
            typeof(PNMarker),
            typeof(PNEndMarker),
            typeof(QTMarker),
            typeof(QTEndMarker),
            typeof(SIGMarker),
            typeof(SIGEndMarker),
            typeof(SLSMarker),
            typeof(SLSEndMarker),
            typeof(WHMarker),
            typeof(WHEndMarker),
            typeof(WJMarker),
            typeof(WJEndMarker),
            typeof(WGMarker),
            typeof(WGEndMarker),
            typeof(WAMarker),
            typeof(WAEndMarker),
            typeof(PRMarker),
            typeof(PROMarker),
            typeof(PROEndMarker),
            typeof(RBMarker),
            typeof(RBEndMarker),
            typeof(QMMarker),
            typeof(FIGMarker),
            typeof(FIGEndMarker),
            typeof(REMMarker),
            typeof(PMarker),
            typeof(PCMarker),
            typeof(TableBlock)
        ]){CanInsert = (type, node, marker) =>
        {
            switch (marker)
            {
                // A verse never holds another verse or a poetry block - those break out.
                // Inline poetry (IsPoetryBlock false) nests under the verse.
                case VMarker:
                case QMarker { IsPoetryBlock: true }:
                    return false;
                default:
                    return true;
            }
        }},
        [typeof(WAMarker)] = new HierarchyDefinition([typeof(TextBlock)]),
        [typeof(WHMarker)] = new HierarchyDefinition([typeof(TextBlock)]),
        [typeof(WGMarker)] = new HierarchyDefinition([typeof(TextBlock)]),
        [typeof(WJMarker)] = new HierarchyDefinition([typeof(TextBlock)]),
        [typeof(XMarker)] = new HierarchyDefinition([
            typeof(XOMarker),
            typeof(XTMarker),
            typeof(XTEndMarker),
            typeof(XQMarker),
            typeof(TextBlock),
        ]),
        [typeof(XOMarker)] = new HierarchyDefinition([typeof(TextBlock)]),
        [typeof(XQMarker)] = new HierarchyDefinition([typeof(TextBlock)]),
        [typeof(XTMarker)] = new HierarchyDefinition([typeof(TextBlock)]),
        [typeof(LIKMarker)] = new HierarchyDefinition([typeof(TextBlock)]),
        [typeof(LITLMarker)] = new HierarchyDefinition([typeof(TextBlock)]),
        [typeof(IPQMarker)] = new HierarchyDefinition([
            typeof(TextBlock),
            typeof(BKMarker),
            typeof(BKEndMarker),
            typeof(BDMarker),
            typeof(BDEndMarker),
            typeof(ITMarker),
            typeof(ITEndMarker),
            typeof(SCMarker),
            typeof(SCEndMarker),
            typeof(BDITMarker),
            typeof(BDITEndMarker),
            typeof(NDMarker),
            typeof(NDEndMarker),
            typeof(NOMarker),
            typeof(NOEndMarker),
            typeof(SUPMarker),
            typeof(SUPEndMarker),
        ]),
    };

    // shared paragraph/paragraph-like presentation children to avoid duplication
    private static readonly Type[] ParagraphPresentationChildren = new[]
    {
         typeof(CMarker),
         typeof(VMarker),
         typeof(BMarker),
         typeof(SPMarker),
         typeof(TextBlock),
         // inline presentation/formatting allowed inside a paragraph
         typeof(TLMarker),
         typeof(TLEndMarker),
         typeof(WMarker),
         typeof(WEndMarker),
         typeof(ITMarker),
         typeof(ITEndMarker),
         typeof(SCMarker),
         typeof(SCEndMarker),
         typeof(SUPMarker),
         typeof(SUPEndMarker),
         // footnote related markers
         typeof(FMarker),
         typeof(FEndMarker),
         typeof(FPMarker),
         typeof(FRMarker),
         typeof(FREndMarker),
         typeof(FVMarker),
         typeof(FVEndMarker),
         typeof(FQMarker),
         typeof(FQEndMarker),
         typeof(FQAMarker),
         typeof(FQAEndMarker),
     };

    // Structure-specific paragraph children must NOT include structural markers (CMarker, VMarker)
    // to avoid creating cycles where paragraphs allow chapters/verses which allow paragraphs.
    private static readonly Type[] ParagraphStructureChildren = ParagraphPresentationChildren
        .Where(t => t != typeof(CMarker) && t != typeof(VMarker))
        .ToArray();

    public static readonly Dictionary<Type, HierarchyDefinition> Presentation = new()
    {
        [typeof(PMarker)] = new HierarchyDefinition(ParagraphPresentationChildren),
        [typeof(QMarker)] = new HierarchyDefinition([
            // allow chapter/verse and common inline markers within quote/poetry blocks
            typeof(CMarker),
            typeof(VMarker),
            typeof(BMarker),
            typeof(QSMarker),
            typeof(QSEndMarker),
            typeof(TextBlock),
            typeof(TLMarker),
            typeof(TLEndMarker),
            typeof(WMarker),
            typeof(WEndMarker),
            typeof(ITMarker),
            typeof(ITEndMarker),
            typeof(SCMarker),
            typeof(SCEndMarker),
            typeof(SUPMarker),
            typeof(SUPEndMarker),
            // footnote support inside quotes/poetry
            typeof(FMarker),
            typeof(FEndMarker),
            typeof(FPMarker),
            typeof(FRMarker),
            typeof(FREndMarker),
            typeof(FVMarker),
            typeof(FVEndMarker),
            typeof(FQMarker),
            typeof(FQEndMarker),
            typeof(FQAMarker),
            typeof(FQAEndMarker),
        ]),
        [typeof(FMarker)] = new HierarchyDefinition([
            // keep existing F-specific children and add common inline/presentation markers
            typeof(FTMarker),
            typeof(FVMarker),
            typeof(FVEndMarker),
            typeof(FPMarker),
            typeof(FQMarker),
            typeof(FQEndMarker),
            typeof(FRMarker),
            typeof(FREndMarker),
            typeof(FKMarker),
            typeof(TextBlock),
            typeof(FQAMarker),
            typeof(FQAEndMarker),
            // inline presentation inside footnotes
            typeof(TLMarker),
            typeof(TLEndMarker),
            typeof(WMarker),
            typeof(WEndMarker),
            typeof(ITMarker),
            typeof(ITEndMarker),
            typeof(SCMarker),
            typeof(SCEndMarker),
            typeof(SUPMarker),
            typeof(SUPEndMarker),
            // reference/book markers often appear in notes
            typeof(BKMarker),
            typeof(BKEndMarker),
            typeof(BDMarker),
            typeof(BDEndMarker),
            typeof(FLMarker),
        ]),
        // paragraph-like markers use the shared children to avoid duplication
        [typeof(PCMarker)] = new HierarchyDefinition(ParagraphPresentationChildren),
        [typeof(PIMarker)] = new HierarchyDefinition(ParagraphPresentationChildren),
        [typeof(PMMarker)] = new HierarchyDefinition(ParagraphPresentationChildren),
        [typeof(PMCMarker)] = new HierarchyDefinition(ParagraphPresentationChildren),
        [typeof(PMOMarker)] = new HierarchyDefinition(ParagraphPresentationChildren),
        [typeof(PMRMarker)] = new HierarchyDefinition(ParagraphPresentationChildren),
        [typeof(PNMarker)] = new HierarchyDefinition(ParagraphPresentationChildren),
        [typeof(PNGMarker)] = new HierarchyDefinition(ParagraphPresentationChildren),
        [typeof(PRMarker)] = new HierarchyDefinition(ParagraphPresentationChildren),
        [typeof(PROMarker)] = new HierarchyDefinition(ParagraphPresentationChildren),
    };

    // A structure-focused hierarchy: chapter -> verse, with paragraphs allowed under either
    public static readonly Dictionary<Type, HierarchyDefinition> Structure = new()
    {
        // Chapter may contain verses and paragraph markers
        [typeof(CMarker)] = new HierarchyDefinition([
            typeof(VMarker),
            typeof(PMarker),
            typeof(PCMarker),
            typeof(PIMarker),
            typeof(PMMarker),
            typeof(PMCMarker),
            typeof(PMOMarker),
            typeof(PMRMarker),
            typeof(PNMarker),
            typeof(PNGMarker),
            typeof(PRMarker),
            typeof(PROMarker),
        ]),

        // Verse may contain paragraph markers
        [typeof(VMarker)] = new HierarchyDefinition([
            typeof(PMarker),
            typeof(PCMarker),
            typeof(PIMarker),
            typeof(PMMarker),
            typeof(PMCMarker),
            typeof(PMOMarker),
            typeof(PMRMarker),
            typeof(PNMarker),
            typeof(PNGMarker),
            typeof(PRMarker),
            typeof(PROMarker),
        ]),

        // Paragraph-like markers use structure-safe children (no CMarker/VMarker to prevent cycles)
        [typeof(PMarker)] = new HierarchyDefinition(ParagraphStructureChildren),
        [typeof(PCMarker)] = new HierarchyDefinition(ParagraphStructureChildren),
        [typeof(PIMarker)] = new HierarchyDefinition(ParagraphStructureChildren),
        [typeof(PMMarker)] = new HierarchyDefinition(ParagraphStructureChildren),
        [typeof(PMCMarker)] = new HierarchyDefinition(ParagraphStructureChildren),
        [typeof(PMOMarker)] = new HierarchyDefinition(ParagraphStructureChildren),
        [typeof(PMRMarker)] = new HierarchyDefinition(ParagraphStructureChildren),
        [typeof(PNMarker)] = new HierarchyDefinition(ParagraphStructureChildren),
        [typeof(PNGMarker)] = new HierarchyDefinition(ParagraphStructureChildren),
        [typeof(PRMarker)] = new HierarchyDefinition(ParagraphStructureChildren),
        [typeof(PROMarker)] = new HierarchyDefinition(ParagraphStructureChildren),
    };
    
    public static readonly List<FrozenDictionary<Type, HierarchyDefinition>> DefaultHierarchyList = 
        [Default.ToFrozenDictionary(), Structure.ToFrozenDictionary(), Presentation.ToFrozenDictionary()];

}
